### PR TITLE
added quickchart and mongodb

### PR DESCRIPTION
**Pull request by RafflesiaKhan**
### What changes were proposed in this pull request?

I have added three new scripts 
- [input-from-mongodb.ipynb](https://github.com/RafflesiaKhan/component-library/blob/add-mondodb-connection/component-library/input/input-from-mongodb.ipynb) ---- for MongoDB connection creation and test
- [visualize-with-quickchart.ipynb](https://github.com/RafflesiaKhan/component-library/blob/add-mondodb-connection/component-library/visualize/visualize-with-quickchart.ipynb) ---- for QuickChart configuration creation and test
- [visualize-with-quickchart-mongodb.ipynb](https://github.com/RafflesiaKhan/component-library/blob/add-mondodb-connection/component-library/visualize/visualize-with-quickchart-mongodb.ipynb) ---- for retrieving data from MongoDB and create analytics using QuickChart

### How was this pull request tested?

These files are tested locally, and they are just making connection and printing data I am not certain which kind of test case I can add here, but I am happy to get any suggestions. 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by romeokienzler** [comment]
Dear @RafflesiaKhan - first of all, thank you so much for your contributions! Here are some things which need to be done before the new code can be merged, otherwise C3 (the CLAIMED component compiler) will fail to create (docker) container images, kubeflow components and CLI support - which usually happens automatically

- [ ] Please make sure the notebooks are clean (no numbering/output) - this helps in resolving conflicts at a later stage - in jupypter lab you can just select 'clear all outputs' in vsCode ' clear all'

- [ ] A use of a component (which gets generated from your code) ideally does not need to edit to code to be used. Therefore, every configuration items needs to be provided from 'the outside' - if you have a look at [this](https://github.com/claimed-framework/component-library/blob/main/component-library/output/upload-to-cos.ipynb) example you will notice that there exists a cell where a lot of environment variables are read. The next cell just does the same for all CLI command line parameters which might be passed to your code - the last cell works for all string type parameters, the first cell (where the env variables are read) you need to adjust to e.g., database url, database name, collection.... - also the document or visialization should not be printed inline but written to a file - the file name should also be specified in that parameter section - please note that output parameter need to start with an 'output_'

**Comment by romeokienzler** [comment]
Dear @RafflesiaKhan just had a look at your latest commit - we're making progress, please note that the _correct_ way to 'ingest' configuration parameters is by reading the environment variables 

so instead of 

`database_username = 'database_username'`

you can write

database_username = os.environ.get('database_username', 'HERE_GOES_A_POTENTIAL_DEFAULT_VALUE')

data_dir is not needed anymore

Please have a look at the template notebook I've provided above, there is a code section which also needs to be added to be able to also 'ingest' configuration parameters via command line arguments

image

**Comment by RafflesiaKhan** [comment]
> Dear @RafflesiaKhan just had a look at your latest commit - we're making progress, please note that the _correct_ way to 'ingest' configuration parameters is by reading the environment variables
> 
> so instead of
> 
> `database_username = 'database_username'`
> 
> you can write
> 
> database_username = os.environ.get('database_username', 'HERE_GOES_A_POTENTIAL_DEFAULT_VALUE')
> 
> data_dir is not needed anymore
> 
> Please have a look at the template notebook I've provided above, there is a code section which also needs to be added to be able to also 'ingest' configuration parameters via command line arguments
> 
> image

@romeokienzler Thanks you so much for the comments, sorry I missed the code section, will update the PR soon

**Comment by RafflesiaKhan** [comment]
Hi @romeokienzler, Thank you so much for the detailed comments; those helped a lot; sorry about all these issues; thanks for being patient. I promise future PRs will be much cleaner 🙂. Please feel free to add comments if any other updates are required here.

**Comment by RafflesiaKhan** [comment]
Hi @romeokienzler, sorry got busy with office work, I have removed the `# temporal data .. `stuff, most of the previous comments are now covered. Please let me know if anything else is required. Thank you.

**Comment by romeokienzler** [comment]
Thanks so much @RafflesiaKhan I think you are almost done. The last thing missing is to remove the 2nd parameter of <<ALL>> calls to the 'get' function in os.environ.get

so instead of 

cluster_url = os.environ.get('cluster_url',"HERE_GOES_YOUR_CLUSTER_URL")

please write 

cluster_url = os.environ.get('cluster_url')

The 2nd parameter to that 'get' function is only there in case the environment variable is not set that there will be a default value set. 

So please go ahead and remove the 2nd parameter in ALL the function calls in ALL the notebooks you have provided and then I think we are good.

One last thing, the CLAIMED component compiler doesn't support multi line comments for the parameters, so instead of

# Input parameters for chart
# chart type
chart_type = os.environ.get('chart_type','HERE_GOES_YOUR_CHART_TYPE')


you should write

# Input parameters for chart, chart type 
chart_type = os.environ.get('chart_type','HERE_GOES_YOUR_CHART_TYPE')

and of course also remove the 2nd parameter

# Input parameters for chart, chart type 
chart_type = os.environ.get('chart_type')

**Review by romeokienzler — APPROVED** [review]

**Comment by romeokienzler** [comment]
Thanks so much @RafflesiaKhan - great work - you are now an official contributor to an IBM sponsored Linux Foundation AI project

[x] merged

**Comment by RafflesiaKhan** [comment]
> Thanks so much @RafflesiaKhan - great work - you are now an official contributor to an IBM sponsored Linux Foundation AI project
> 
> [x] merged

Yeaaaaaa 😎. I truly appreciate your encouragement, @romeokienzler! It has been such an amazing experience so far and I'm looking forward to continuing my journey as a contributor. Thank you so much for your support! 🙂

**Pull request merged**
